# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jford/scout24/vipser

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jford/scout24/vipser

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jford/scout24/vipser/CMakeFiles /Users/jford/scout24/vipser/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jford/scout24/vipser/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sniffer

# Build rule for target.
sniffer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sniffer
.PHONY : sniffer

# fast build rule for target.
sniffer/fast:
	$(MAKE) -f CMakeFiles/sniffer.dir/build.make CMakeFiles/sniffer.dir/build
.PHONY : sniffer/fast

#=============================================================================
# Target rules for targets named vipser

# Build rule for target.
vipser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vipser
.PHONY : vipser

# fast build rule for target.
vipser/fast:
	$(MAKE) -f CMakeFiles/vipser.dir/build.make CMakeFiles/vipser.dir/build
.PHONY : vipser/fast

src/io.o: src/io.c.o

.PHONY : src/io.o

# target to build an object file
src/io.c.o:
	$(MAKE) -f CMakeFiles/sniffer.dir/build.make CMakeFiles/sniffer.dir/src/io.c.o
	$(MAKE) -f CMakeFiles/vipser.dir/build.make CMakeFiles/vipser.dir/src/io.c.o
.PHONY : src/io.c.o

src/io.i: src/io.c.i

.PHONY : src/io.i

# target to preprocess a source file
src/io.c.i:
	$(MAKE) -f CMakeFiles/sniffer.dir/build.make CMakeFiles/sniffer.dir/src/io.c.i
	$(MAKE) -f CMakeFiles/vipser.dir/build.make CMakeFiles/vipser.dir/src/io.c.i
.PHONY : src/io.c.i

src/io.s: src/io.c.s

.PHONY : src/io.s

# target to generate assembly for a file
src/io.c.s:
	$(MAKE) -f CMakeFiles/sniffer.dir/build.make CMakeFiles/sniffer.dir/src/io.c.s
	$(MAKE) -f CMakeFiles/vipser.dir/build.make CMakeFiles/vipser.dir/src/io.c.s
.PHONY : src/io.c.s

src/sniffer.o: src/sniffer.c.o

.PHONY : src/sniffer.o

# target to build an object file
src/sniffer.c.o:
	$(MAKE) -f CMakeFiles/sniffer.dir/build.make CMakeFiles/sniffer.dir/src/sniffer.c.o
.PHONY : src/sniffer.c.o

src/sniffer.i: src/sniffer.c.i

.PHONY : src/sniffer.i

# target to preprocess a source file
src/sniffer.c.i:
	$(MAKE) -f CMakeFiles/sniffer.dir/build.make CMakeFiles/sniffer.dir/src/sniffer.c.i
.PHONY : src/sniffer.c.i

src/sniffer.s: src/sniffer.c.s

.PHONY : src/sniffer.s

# target to generate assembly for a file
src/sniffer.c.s:
	$(MAKE) -f CMakeFiles/sniffer.dir/build.make CMakeFiles/sniffer.dir/src/sniffer.c.s
.PHONY : src/sniffer.c.s

src/sniffing.o: src/sniffing.c.o

.PHONY : src/sniffing.o

# target to build an object file
src/sniffing.c.o:
	$(MAKE) -f CMakeFiles/sniffer.dir/build.make CMakeFiles/sniffer.dir/src/sniffing.c.o
	$(MAKE) -f CMakeFiles/vipser.dir/build.make CMakeFiles/vipser.dir/src/sniffing.c.o
.PHONY : src/sniffing.c.o

src/sniffing.i: src/sniffing.c.i

.PHONY : src/sniffing.i

# target to preprocess a source file
src/sniffing.c.i:
	$(MAKE) -f CMakeFiles/sniffer.dir/build.make CMakeFiles/sniffer.dir/src/sniffing.c.i
	$(MAKE) -f CMakeFiles/vipser.dir/build.make CMakeFiles/vipser.dir/src/sniffing.c.i
.PHONY : src/sniffing.c.i

src/sniffing.s: src/sniffing.c.s

.PHONY : src/sniffing.s

# target to generate assembly for a file
src/sniffing.c.s:
	$(MAKE) -f CMakeFiles/sniffer.dir/build.make CMakeFiles/sniffer.dir/src/sniffing.c.s
	$(MAKE) -f CMakeFiles/vipser.dir/build.make CMakeFiles/vipser.dir/src/sniffing.c.s
.PHONY : src/sniffing.c.s

src/vips_glue.o: src/vips_glue.c.o

.PHONY : src/vips_glue.o

# target to build an object file
src/vips_glue.c.o:
	$(MAKE) -f CMakeFiles/vipser.dir/build.make CMakeFiles/vipser.dir/src/vips_glue.c.o
.PHONY : src/vips_glue.c.o

src/vips_glue.i: src/vips_glue.c.i

.PHONY : src/vips_glue.i

# target to preprocess a source file
src/vips_glue.c.i:
	$(MAKE) -f CMakeFiles/vipser.dir/build.make CMakeFiles/vipser.dir/src/vips_glue.c.i
.PHONY : src/vips_glue.c.i

src/vips_glue.s: src/vips_glue.c.s

.PHONY : src/vips_glue.s

# target to generate assembly for a file
src/vips_glue.c.s:
	$(MAKE) -f CMakeFiles/vipser.dir/build.make CMakeFiles/vipser.dir/src/vips_glue.c.s
.PHONY : src/vips_glue.c.s

src/vipser.o: src/vipser.c.o

.PHONY : src/vipser.o

# target to build an object file
src/vipser.c.o:
	$(MAKE) -f CMakeFiles/vipser.dir/build.make CMakeFiles/vipser.dir/src/vipser.c.o
.PHONY : src/vipser.c.o

src/vipser.i: src/vipser.c.i

.PHONY : src/vipser.i

# target to preprocess a source file
src/vipser.c.i:
	$(MAKE) -f CMakeFiles/vipser.dir/build.make CMakeFiles/vipser.dir/src/vipser.c.i
.PHONY : src/vipser.c.i

src/vipser.s: src/vipser.c.s

.PHONY : src/vipser.s

# target to generate assembly for a file
src/vipser.c.s:
	$(MAKE) -f CMakeFiles/vipser.dir/build.make CMakeFiles/vipser.dir/src/vipser.c.s
.PHONY : src/vipser.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sniffer"
	@echo "... vipser"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
	@echo "... src/sniffer.o"
	@echo "... src/sniffer.i"
	@echo "... src/sniffer.s"
	@echo "... src/sniffing.o"
	@echo "... src/sniffing.i"
	@echo "... src/sniffing.s"
	@echo "... src/vips_glue.o"
	@echo "... src/vips_glue.i"
	@echo "... src/vips_glue.s"
	@echo "... src/vipser.o"
	@echo "... src/vipser.i"
	@echo "... src/vipser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

